spring:
  application:
    name: mud-world

---
spring:
  profiles: default
  datasource:
    platform: h2
 
---
spring:
  profiles: dev
  
  datasource:
    platform: postgres
    url: jdbc:postgresql://mudengine.c2v9hbjh7mbw.us-east-2.rds.amazonaws.com:5432/mudenginedb
    username: mudengine_world_app
    password: mudengine_world_app
    
    tomcat:
      max-active: 5
      max-wait: 15000 

  activemq:
    broker-url: ssl://b-89f2515b-5e00-4f47-a3e1-af19d7ad82d8-1.mq.us-east-2.amazonaws.com:61617

server:
  port: 8080  
  
place:
  topic: VirtualTopic.place
  
token:
  secret: a7ac498c7bba59e0eb7c647d2f0197f8