server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    region: am-south

spring:
  application:
    name: mud-registry

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF