version: '3.6'
services:
  mud-world:
    build:
      context: ../../mud-world/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-world
    ports:
      - 8082:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg
    extra_hosts:
      - "database:${DB_HOST}"
      - "rabbitmq:${MQ_HOST}"
      - "consul:${CONSUL_HOST}"
      - "vault:${VAULT_HOST}"
    networks:
      - net
  mud-item:
    build:
      context: ../../mud-item/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-item
    ports:
      - 8084:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
    extra_hosts:
      - "database:${DB_HOST}"
      - "rabbitmq:${MQ_HOST}"
      - "consul:${CONSUL_HOST}"
      - "vault:${VAULT_HOST}"
    networks:
      - net
  mud-being:
    build:
      context: ../../mud-being/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-being
    ports:
      - 8086:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
    extra_hosts:
      - "database:${DB_HOST}"
      - "rabbitmq:${MQ_HOST}"
      - "consul:${CONSUL_HOST}"
      - "vault:${VAULT_HOST}"
    networks:
      - net
  mud-message:
    build:
      context: ../../mud-message/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-message
    ports:
      - 8088:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
    extra_hosts:
      - "database:${DB_HOST}"
      - "consul:${CONSUL_HOST}"
      - "vault:${VAULT_HOST}"
    networks:
      - net
  mud-action:
    build:
      context: ../../mud-action/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-action
    ports:
      - 8090:8080
    environment:          
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
    extra_hosts:
      - "database:${DB_HOST}"
      - "rabbitmq:${MQ_HOST}"
      - "consul:${CONSUL_HOST}"
      - "vault:${VAULT_HOST}"
    networks:
      - net
  mud-player:
    build:
      context: ../../mud-player/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-player
    ports:
      - 8092:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
      # To enable email sending, uncomment the lines below and provide valid credentials
      #- SMTP_HOST=smtp.email.com
      #- SMTP_PORT=587
      #- SMTP_FROM=someemail@email.com
      #- SMTP_USER=someemail@email.com
      #- SMTP_PWD=
    extra_hosts:
      - "database:${DB_HOST}"
      - "consul:${CONSUL_HOST}"
      - "vault:${VAULT_HOST}"
    networks:
      - net
  mud-api:
    build:
      context: ../../mud-api/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-api
    ports:
      - 8080:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - SPRING_PROFILES_ACTIVE=itg      
    extra_hosts:
      - "consul:${CONSUL_HOST}"
    networks:
      - net  
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 171.27.0.0/16
