spring:
  application:
    name: mud-config
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/mud-config

management:
  info:
    build:
      enabled: true
  security:
    enabled: true
      
endpoints:
  info:
    enabled: true
    sensitive: false

server:
  port: 8888      
          
---

spring:
  profiles: itgtest         
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JosielOliveira/mud-config
      username: ${GIT_USERNAME}
      password: ${GIT_PASSWORD}
