version: '3.6'
services:
  consul:
    image: consul:latest
    ports:
      - 8500:8500
    networks:
      - app_net
  consul-loader:
    build:
      context: ../../consul/local
      dockerfile: ./Dockerfile  
    image: mudengine/consul-loader
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    command: consul kv import @data.json      
    networks:
      - app_net
    depends_on:
      - consul
  vault:
    image: vault:0.8.3
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    cap_add:
      - IPC_LOCK      
    networks:
      - app_net
  vault-loader:
    build:
      context: ../../vault/local
      dockerfile: ./Dockerfile
    image: mudengine/vault-loader
    environment:
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
    command: ./vault-initialize.sh
    depends_on:
      - vault
    networks:
      - app_net
  mud-world:
    build:
      context: ../../../mud-world/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-world
    ports:
      - 8082:8080
    environment:
      - EXPOSED_PORT=8082
      - EXPOSED_HOST=10.1.11.65      
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=qa
    networks:
      - app_net
    depends_on:
      - consul-loader
      - vault-loader
  mud-item:
    build:
      context: ../../../mud-item/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-item
    ports:
      - 8084:8080
    environment:
      - EXPOSED_PORT=8084
      - EXPOSED_HOST=10.1.11.65      
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=qa      
    networks:
      - app_net
  mud-being:
    build:
      context: ../../../mud-being/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-being
    ports:
      - 8086:8080
    environment:
      - EXPOSED_PORT=8086
      - EXPOSED_HOST=10.1.11.65      
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=qa      
    networks:
      - app_net
  mud-message:
    build:
      context: ../../../mud-message/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-message
    ports:
      - 8088:8080
    environment:
      - EXPOSED_PORT=8088
      - EXPOSED_HOST=10.1.11.65      
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=qa      
    networks:
      - app_net
  mud-action:
    build:
      context: ../../../mud-action/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-action
    ports:
      - 8090:8080
    environment:
      - EXPOSED_PORT=8090
      - EXPOSED_HOST=10.1.11.65            
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=qa      
    networks:
      - app_net
  mud-player:
    build:
      context: ../../../mud-player/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-player
    ports:
      - 8092:8080
    environment:
      - EXPOSED_PORT=8092
      - EXPOSED_HOST=10.1.11.65
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=qa      
    networks:
      - app_net
  mud-api:
    build:
      context: ../../../mud-api/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-api
    ports:
      - 8080:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - SPRING_PROFILES_ACTIVE=qa      
    networks:
      - app_net  
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 170.27.0.0/16
