version: '3.6'
services:
  mud-world:
    build:
      context: ../../mud-world/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-world
    ports:
      - 8082:8080
    environment:
      - EXPOSED_PORT=8082
      - EXPOSED_HOST=localhost
      - CONFIG_SERVER_URL=http://mud-config:8888/
      - EUREKA_SERVER_URL=http://mud-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
    depends_on:
      - mud-config
      - mud-registry
  mud-item:
    build:
      context: ../../mud-item/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-item
    ports:
      - 8084:8080
    environment:
      - EXPOSED_PORT=8084
      - EXPOSED_HOST=localhost
      - CONFIG_SERVER_URL=http://mud-config:8888/
      - EUREKA_SERVER_URL=http://mud-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
    depends_on:
      - mud-config
      - mud-registry
  mud-being:
    build:
      context: ../../mud-being/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-being
    ports:
      - 8086:8080
    environment:
      - EXPOSED_PORT=8086
      - EXPOSED_HOST=localhost
      - CONFIG_SERVER_URL=http://mud-config:8888/
      - EUREKA_SERVER_URL=http://mud-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
    depends_on:
      - mud-config
      - mud-registry
  mud-message:
    build:
      context: ../../mud-message/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-message
    ports:
      - 8088:8080
    environment:
      - EXPOSED_PORT=8088
      - EXPOSED_HOST=localhost
      - CONFIG_SERVER_URL=http://mud-config:8888/
      - EUREKA_SERVER_URL=http://mud-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
    depends_on:
      - mud-config
      - mud-registry
  mud-action:
    build:
      context: ../../mud-action/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-action
    ports:
      - 8090:8080
    environment:
      - EXPOSED_PORT=8090
      - EXPOSED_HOST=localhost
      - CONFIG_SERVER_URL=http://mud-config:8888/
      - EUREKA_SERVER_URL=http://mud-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
    depends_on:
      - mud-config
      - mud-registry
  mud-player:
    build:
      context: ../../mud-player/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-player
    ports:
      - 8092:8080
    environment:
      - EXPOSED_PORT=8092
      - EXPOSED_HOST=localhost
      - CONFIG_SERVER_URL=http://mud-config:8888/
      - EUREKA_SERVER_URL=http://mud-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
    depends_on:
      - mud-config
      - mud-registry
  mud-api:
    image: mudengine/mud-api
    ports:
      - 8080:8080
    environment:
      - EXPOSED_HOST=localhost
      - EUREKA_SERVER_URL=http://mud-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net  
    depends_on:
      - mud-registry      
  mud-config:
    build:
      context: ../../mud-config/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-config
    ports:
      - 8888:8888
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GIT_USERNAME
      - GIT_PASSWORD
    networks:
      - app_net
  mud-registry:
    build:
      context: ../../mud-registry/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-registry
    ports:
      - 8761:8761
    networks:
      - app_net
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 170.27.0.0/16

 