spring:
  application:
    name: mud-api

eureka:
  client:
    enabled: false


---

spring:
  profiles: itg, qa, prod
  
server:
  port: 8080
  
eureka:
  client:
    enabled: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
