spring:
  application:
    name: mud-api

  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false

---

spring:
  profiles: itg, qa, prod
  
  cloud:
    consul:
      enabled: true
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enabled: true
        register: false

server:
  port: 8080