spring:
  application:
    name: mud-api

  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
        
zuul:
  ignored-services: "*"
  routes:
    place:
      path: /place/**
      serviceId: mud-world
      strip-prefix: false
    item:
      path: /item/**
      serviceId: mud-item
      strip-prefix: false
    being:
      path: /being/**
      serviceId: mud-being
      strip-prefix: false
    message:
      path: /message/**
      serviceId: mud-message
      strip-prefix: false
    player:
      path: /player/**
      serviceId: mud-player
      strip-prefix: false
    action:
      path: /action/**
      serviceId: mud-action
      strip-prefix: false
      

ribbon:
  ReadTimeout: 10000


---

spring:
  profiles: itg, qa, prod
  
  cloud:
    consul:
      enabled: true
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enabled: true
        register: false

server:
  port: 8080