version: '3.6'
services:
  nosqldb:
    build:
      context: ./mongodb
      dockerfile: ./Dockerfile
    image: mudengine/mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    ports:
      - 27017:27017
    networks:
      - net
  elsearch:
    image: elasticsearch:5.6.12
    environment:
      - node.name=mud-search
      - discovery_type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        hard: -1
        soft: -1
    networks:
      - net
  graylog:
    image: graylog/graylog:2.4
    environment:
      - GRAYLOG_PASSWORD_SECRET=ThisIsASecretHandGenerated
      - GRAYLOG_ROOT_USERNAME=mudlog
      - GRAYLOG_ROOT_PASSWORD_SHA2=850334960E17F8656CF2BA135D9044FA0C9F9C593589C5699BB0C0CBB325145A
      - GRAYLOG_MONGODB_URI=mongodb://mudlog:mudlog@nosqldb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elsearch:9200
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      - 12201:12201
      - 12201:12201/udp
    networks:
      - net
    depends_on:
      - nosqldb
      - elsearch
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      #- ./rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw
    networks:
      - net
  database:
    build:
      context: ./postgres/docker
      dockerfile: ./Dockerfile
    image: mudengine/postgres
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mudengine
    #volumes:
    #    - type: bind
    #      source: ./postgres/data
    #      target: /var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - net
  consul:
    image: consul:latest
    ports:
      - 8500:8500
    networks:
      - net
  consul-loader:
    build:
      context: ./consul
      dockerfile: ./Dockerfile  
    image: mudengine/consul-loader
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    command: consul kv import @data.json      
    networks:
      - net
    depends_on:
      - consul
      - database      
  vault:
    image: vault:0.8.3
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    cap_add:
      - IPC_LOCK      
    networks:
      - net
  vault-loader:
    build:
      context: ./vault
      dockerfile: ./Dockerfile
    image: mudengine/vault-loader
    environment:
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
    command: ./vault-initialize.sh
    depends_on:
      - vault
    networks:
      - net
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 170.27.0.0/16
