version: '3.6'
services:
  consul:
    image: consul:latest
    ports:
      - 8500:8500
    networks:
      - net
  consul-loader:
    build:
      context: ./consul
      dockerfile: ./Dockerfile  
    image: mudengine/consul-loader
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    command: consul kv import @data.json      
    networks:
      - net
    depends_on:
      - consul
  vault:
    image: vault:0.8.3
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    cap_add:
      - IPC_LOCK      
    networks:
      - net
  vault-loader:
    build:
      context: ./vault
      dockerfile: ./Dockerfile
    image: mudengine/vault-loader
    environment:
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
    command: ./vault-initialize.sh
    depends_on:
      - vault
    networks:
      - net
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 170.27.0.0/16
