version: '3.6'
services:
  infra:  
    image: hello-world
    networks:
      - app_net
    depends_on:
      - consul-loader
      - vault-loader
      - database
      - rabbitmq    
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      #- ./rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw
    networks:
      - app_net
  database:
    build:
      context: ./postgres/docker
      dockerfile: ./Dockerfile
    image: mudengine/postgres
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mudengine
    #volumes:
    #    - type: bind
    #      source: ./postgres/data
    #      target: /var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - app_net
  consul:
    image: consul:latest
    ports:
      - 8500:8500
    networks:
      - app_net
  consul-loader:
    build:
      context: ./consul
      dockerfile: ./Dockerfile  
    image: mudengine/consul-loader
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    command: consul kv import @data.json      
    networks:
      - app_net
    depends_on:
      - consul
      - database      
  vault:
    image: vault:0.8.3
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    cap_add:
      - IPC_LOCK      
    networks:
      - app_net
  vault-loader:
    build:
      context: ./vault
      dockerfile: ./Dockerfile
    image: mudengine/vault-loader
    environment:
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
    command: ./vault-initialize.sh
    depends_on:
      - vault
    networks:
      - app_net
  mud-world:
    build:
      context: ../mud-world/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-world
    ports:
      - 8082:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg
    networks:
      - app_net
    depends_on:
      - consul-loader
      - vault-loader
      - database
      - rabbitmq
  mud-item:
    build:
      context: ../mud-item/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-item
    ports:
      - 8084:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
    networks:
      - app_net
    depends_on:
      - consul-loader
      - vault-loader
      - database
      - rabbitmq      
  mud-being:
    build:
      context: ../mud-being/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-being
    ports:
      - 8086:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
    networks:
      - app_net
    depends_on:
      - consul-loader
      - vault-loader
      - database      
      - rabbitmq
  mud-message:
    build:
      context: ../mud-message/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-message
    ports:
      - 8088:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
    networks:
      - app_net
    depends_on:
      - consul-loader
      - vault-loader
      - database      
  mud-action:
    build:
      context: ../mud-action/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-action
    ports:
      - 8090:8080
    environment:          
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
    networks:
      - app_net
    depends_on:
      - consul-loader
      - vault-loader
      - database
      - rabbitmq
  mud-player:
    build:
      context: ../mud-player/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-player
    ports:
      - 8092:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault:8200
      - SPRING_PROFILES_ACTIVE=itg      
      # To enable email sending, uncomment the lines below and provide valid credentials
      #- SMTP_HOST=smtp.email.com
      #- SMTP_PORT=587
      #- SMTP_FROM=someemail@email.com
      #- SMTP_USER=someemail@email.com
      #- SMTP_PWD=
    networks:
      - app_net
    depends_on:
      - consul-loader
      - vault-loader
      - database      
  mud-api:
    build:
      context: ../mud-api/
      dockerfile: ./Dockerfile  
    image: mudengine/mud-api
    ports:
      - 8080:8080
    environment:
      - CONSUL_HOST=http://consul
      - CONSUL_PORT=8500
      - SPRING_PROFILES_ACTIVE=itg      
    networks:
      - app_net  
    depends_on:
      - consul-loader
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 170.27.0.0/16
