version: '3.6'
services:
  mud-world:
    image: mudengine/mud-world
    ports:
      - 8082:8080    
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      - EXPOSED_PORT=8082    
      - EXPOSED_HOST=jeremias
      - CONSUL_HOST=http://jeremias
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://jeremias:8200
      - VAULT_TOKEN=62c0b35b-203f-72ec-3539-0a3698a0587c
      - SPRING_PROFILES_ACTIVE=qa
    networks:
      - app_net
  mud-item:
    image: mudengine/mud-item
    ports:
      - 8084:8080    
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      - EXPOSED_PORT=8084
      - EXPOSED_HOST=jeremias
      - CONSUL_HOST=http://jeremias
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://jeremias:8200
      - VAULT_TOKEN=62c0b35b-203f-72ec-3539-0a3698a0587c
      - SPRING_PROFILES_ACTIVE=qa
    networks:
      - app_net
  mud-being:
    image: mudengine/mud-being
    ports:
      - 8086:8080    
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M      
    environment:
      - EXPOSED_PORT=8086
      - EXPOSED_HOST=jeremias
      - CONSUL_HOST=http://jeremias
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://jeremias:8200
      - VAULT_TOKEN=62c0b35b-203f-72ec-3539-0a3698a0587c
      - SPRING_PROFILES_ACTIVE=qa
    networks:
      - app_net
  mud-message:
    image: mudengine/mud-message
    ports:
      - 8088:8080    
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      - EXPOSED_PORT=8088
      - EXPOSED_HOST=jeremias
      - CONSUL_HOST=http://jeremias
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://jeremias:8200
      - VAULT_TOKEN=62c0b35b-203f-72ec-3539-0a3698a0587c
      - SPRING_PROFILES_ACTIVE=qa
    networks:
      - app_net
  mud-action:
    image: mudengine/mud-action
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - 8090:8080
    environment:
      - EXPOSED_PORT=8090
      - EXPOSED_HOST=jeremias
      - CONSUL_HOST=http://jeremias
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://jeremias:8200
      - VAULT_TOKEN=62c0b35b-203f-72ec-3539-0a3698a0587c
      - SPRING_PROFILES_ACTIVE=qa
    networks:
      - app_net
  mud-player:
    image: mudengine/mud-player
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - 8092:8080
    environment:
      - EXPOSED_PORT=8092
      - EXPOSED_HOST=jeremias
      - CONSUL_HOST=http://jeremias
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://jeremias:8200
      - VAULT_TOKEN=62c0b35b-203f-72ec-3539-0a3698a0587c
      - SPRING_PROFILES_ACTIVE=qa
    networks:
      - app_net
  mud-api:
    image: mudengine/mud-api
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - 8080:8080
    environment:
      - CONSUL_HOST=http://jeremias
      - CONSUL_PORT=8500
      - SPRING_PROFILES_ACTIVE=qa
    networks:
      - app_net  
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 170.27.0.0/16
