spring:
  application:
    name: mud-action
  datasource:
    platform: h2
    initialize: true
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true

server:
  port: 8088
  
eureka:
  client:
    enabled: false
