version: '3.6'
services:
  mud-world:
    image: mudengine/mud-world
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - CONSUL_HOST=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com:8200
      - VAULT_TOKEN=393bda7d-c44a-2c33-6d69-c8d47c83094a
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
  mud-item:
    image: mudengine/mud-item
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - CONSUL_HOST=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com:8200
      - VAULT_TOKEN=393bda7d-c44a-2c33-6d69-c8d47c83094a
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
  mud-being:
    image: mudengine/mud-being
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M      
    environment:
      - CONSUL_HOST=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com:8200
      - VAULT_TOKEN=393bda7d-c44a-2c33-6d69-c8d47c83094a
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
  mud-message:
    image: mudengine/mud-message
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - CONSUL_HOST=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com:8200
      - VAULT_TOKEN=393bda7d-c44a-2c33-6d69-c8d47c83094a
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
  mud-action:
    image: mudengine/mud-action
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - CONSUL_HOST=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com:8200
      - VAULT_TOKEN=393bda7d-c44a-2c33-6d69-c8d47c83094a
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
  mud-player:
    image: mudengine/mud-player
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - CONSUL_HOST=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com
      - CONSUL_PORT=8500
      - VAULT_ADDR=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com:8200
      - VAULT_TOKEN=393bda7d-c44a-2c33-6d69-c8d47c83094a
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net
  mud-api:
    image: mudengine/mud-api
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    ports:
      - 8080:8080
    environment:
      - CONSUL_HOST=http://ec2-52-14-59-146.us-east-2.compute.amazonaws.com
      - CONSUL_PORT=8500
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net  
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 170.27.0.0/16
